version: '3.5'

services:
  db:
    container_name: travelence_db
    image: travelence_db_1
    environment:
      POSTGRES_USER: travelence
      POSTGRES_PASSWORD: traveldb
      PGDATA: /data/travelence
    volumes:
       - db-volume:/bitnami/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile

volumes:
  db-volume:
     name: db-volume